### ISSUE TITLE
Adding Email validator in Schema .

### ISSUE THREAD

**Issue by Anmolag111** [OpenSouceCode/Backend#44] opened 2020-08-26 19:46 UTC
Each key in the UserSchema defines a property in documents which will be cast to its associated SchemaType. But email requires special validation since there is no validation on the email property in the UserSchema . So using mongoose-type-email which is an email field-type for Mongoose schemas ensures validated enteries of emails in database.

**Comment by iampavangandhi** [comment] 2020-10-01 04:51
@Anmolag111 Is the issue still present? There is no email field in ```User.js``` model

**Comment by Dishebh** [comment] 2020-10-01 05:42
The issue isn't required for now. Therefore, closing it :)

**Closed by Dishebh** 2020-10-01 05:42 UTC
Labels: enhancement
